# Generated by Django 3.1.6 on 2021-02-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='quantity',
            new_name='initial_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_item',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_left',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
            preserve_default=False,
        ),
    ]
